enforce_secure_profile: false
listeners:
- query_port: 25565
  motd: |
    &8              &m  ]&f&m-    &r &a&lNew Lands &f&m    -&8&m[  &r
    &7&l          1.19.4 Survival Community
  tab_list: SERVER
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 69.129.212.211:25565
  max_players: 50
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 1
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 5000
log_commands: false
stats: 9c345aca-5737-41b9-a651-2c75cea65065
online_mode: true
forge_support: true
disabled_commands:
- server
- servers
servers:
  lobby:
    motd: |
      &8              &m  ]&f&m-    &r &a&lNew Lands &f&m    -&8&m[  &r
      &7&l          1.19.4 Survival Community
    address: localhost:25568
    restricted: false
  survival:
    motd: |
      &8              &m  ]&f&m-    &r &a&lNew Lands &f&m    -&8&m[  &r
      &7&l          1.19.4 Survival Community
    address: localhost:25567
    restricted: false
  creative:
    motd: |
      &8              &m  ]&f&m-    &r &a&lNew Lands &f&m    -&8&m[  &r
      &7&l          1.19.4 Survival Community
    address: localhost:25569
    restricted: false
